import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import pcktsc from "../public/pcktsc.jpg"
import hsn from "../public/hsn.png";
import pwdgen from "../public/pwdgen.png";
import JATE from "../public/JATE.png";
import ntTkr from "../public/ntTkr.png";
import qcP from "../public/qcP.png";
import wkdyschd from "../public/wkdyschd.png";
import loaflounge from "../public/loaflounge.png";
import profRDMgen from "../public/profRDMgen.png";
import tmPrflgen from "../public/tmPrflgen.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>NF Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">tedTalkTimmy</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  target="_blank"
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://www.linkedin.com/in/fortunatonatanael/"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Natanael Fortunato
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I am a developer who enjoys, primarily, backend work.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.twitter.com/wahlwoodsman"><AiFillTwitterCircle /></a>
              <a href="https://www.linkedin.com/in/fortunatonatanael/"><AiFillLinkedin /></a>
              <a href="https://www.github.com/tedtalktimmy"><AiFillGithub /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src="/avatar.png" layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Technologies
              </h3>
              <p className="py-2">
                I have currently created projects using the following technologies:
              </p>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS (Custom and Tailwind)</p>
              <p className="text-gray-800 py-1">javaScript</p>
              <p className="text-gray-800 py-1">MongoDB</p>
              <p className="text-gray-800 py-1">MySQL</p>
              <p className="text-gray-800 py-1">NoSQL</p>
              <p className="text-gray-800 py-1">MERN Stack</p>
              <p className="text-gray-800 py-1">Node</p>
              <p className="text-gray-800 py-1">Handlebars</p>
              <p className="text-gray-800 py-1">API Implementation</p>
              <p className="text-gray-800 py-1">React</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I am new in my coding journey, but I have really enjoyed pushing myself to
              <span className="text-teal-500"> further expand my knowledge </span>
              and apply it to <span className="text-teal-500">projects </span>
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Feel free to take a look at some of the projects I have worked on!
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <a target="_blank" href="https://macabre-coffin-65160.herokuapp.com/">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={pcktsc}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a target="_blank" href="https://evening-river-11733.herokuapp.com/">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={qcP}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a target="_blank" href="https://intense-mountain-48692.herokuapp.com/">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={ntTkr}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 ">
              <a target="_blank" href="https://github.com/tedtalktimmy/horiseon-refactor-project">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={hsn}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a target="_blank" href="https://github.com/tedtalktimmy/pwd.generator-jS">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={pwdgen}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a target="_blank" href="https://tedtalktimmy.github.io/work-day-scheduler/">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={wkdyschd}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a target="_blank" href="https://agile-wave-79744.herokuapp.com">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={JATE}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a target="_blank" href="https://tedtalktimmy.github.io/project01/">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={loaflounge}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a target="_blank" href="https://github.com/tedtalktimmy/team-profile-generator">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={tmPrflgen}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a target="_blank" href="https://github.com/tedtalktimmy/professional-README-generator">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={profRDMgen}
                />
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
